Support cross-compiling

diff --git a/kasld b/kasld
--- a/kasld
+++ b/kasld
@@ -9,7 +9,6 @@
 # 2019 - <bcoles@gmail.com>
 
 base_dir="$(dirname "$(readlink -f "$0")")"
-build="${base_dir}/build"
 
 cd "${base_dir}" || exit 1
 
@@ -31,166 +30,8 @@ echo "Readable /var/log/dmesg:     $(test -r /var/log/dmesg && echo yes || echo 
 echo "Readable /var/log/kern.log:  $(test -r /var/log/kern.log && echo yes || echo no)"
 echo "Readable /var/log/syslog:    $(test -r /var/log/syslog && echo yes || echo no)"
 echo "Readable /boot/System.map:   $(test -r /boot/System.map-$(uname -r) && echo yes || echo no)"
+echo "Readable /boot/config:       $(test -r /boot/config-$(uname -r) && echo yes || echo no)"
 echo "Readable DebugFS:            $(test -r /sys/kernel/debug && echo yes || echo no)"
 echo
 
-echo "Building ..."
-echo
-
-make || echo "build failed!"
-echo
-
-echo "Running build ..."
-echo
-
-# leave default as first
-if [ -x "${build}/default.o" ]; then
-  "${build}/default.o"
-  echo
-fi
-
-if [ -x "${build}/boot-config.o" ]; then
-  "${build}/boot-config.o"
-  echo
-fi
-
-if [ -x "${build}/cmdline.o" ]; then
-  "${build}/cmdline.o"
-  echo
-fi
-
-if [ -x "${build}/bcm_msg_head_struct.o" ]; then
-  "${build}/bcm_msg_head_struct.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_android_ion_snapshot.o" ]; then
-  "${build}/dmesg_android_ion_snapshot.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_backtrace.o" ]; then
-  "${build}/dmesg_backtrace.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_check_for_initrd.o" ]; then
-  "${build}/dmesg_check_for_initrd.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_driver_component_ops.o" ]; then
-  "${build}/dmesg_driver_component_ops.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_early_init_dt_add_memory_arch.o" ]; then
-  "${build}/dmesg_early_init_dt_add_memory_arch.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_ex_handler_msr.o" ]; then
-  "${build}/dmesg_ex_handler_msr.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_fake_numa_init.o" ]; then
-  "${build}/dmesg_fake_numa_init.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_free_area_init_node.o" ]; then
-  "${build}/dmesg_free_area_init_node.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_free_reserved_area.o" ]; then
-  "${build}/dmesg_free_reserved_area.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_kaslr-disabled.o" ]; then
-  "${build}/dmesg_kaslr-disabled.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_mem_init_kernel_layout.o" ]; then
-  "${build}/dmesg_mem_init_kernel_layout.o"
-  echo
-fi
-
-if [ -x "${build}/dmesg_mmu_idmap.o" ]; then
-  "${build}/dmesg_mmu_idmap.o"
-  echo
-fi
-
-if [ -x "${build}/entrybleed.o" ]; then
-  "${build}/entrybleed.o"
-  echo
-fi
-
-if [ -x "${build}/mmap-brute-vmsplit.o" ]; then
-  "${build}/mmap-brute-vmsplit.o"
-  echo
-fi
-
-if [ -x "${build}/perf_event_open.o" ]; then
-  "${build}/perf_event_open.o"
-  echo
-fi
-
-if [ -x "${build}/pppd_kallsyms.o" ]; then
-  "${build}/pppd_kallsyms.o"
-  echo
-fi
-
-if [ -x "${build}/proc-config.o" ]; then
-  "${build}/proc-config.o"
-  echo
-fi
-
-if [ -x "${build}/proc-kallsyms.o" ]; then
-  "${build}/proc-kallsyms.o"
-  echo
-fi
-
-if [ -x "${build}/proc-modules.o" ]; then
-  "${build}/proc-modules.o"
-  echo
-fi
-
-if [ -x "${build}/proc-pid-syscall.o" ]; then
-  "${build}/proc-pid-syscall.o"
-  echo
-fi
-
-if [ -x "${build}/proc-stat-wchan.o" ]; then
-  "${build}/proc-stat-wchan.o"
-  echo
-fi
-
-if [ -x "${build}/sysfs_iscsi_transport_handle.o" ]; then
-  "${build}/sysfs_iscsi_transport_handle.o"
-  echo
-fi
-
-if [ -x "${build}/sysfs-kernel-notes-xen.o" ]; then
-  "${build}/sysfs-kernel-notes-xen.o"
-  echo
-fi
-
-if [ -x "${build}/sysfs-module-sections.o" ]; then
-  "${build}/sysfs-module-sections.o"
-  echo
-fi
-
-if [ -x "${build}/sysfs_nf_conntrack.o" ]; then
-  "${build}/sysfs_nf_conntrack.o"
-  echo
-fi
-
-# slow - leave last
-if [ -x "${build}/mincore.o" ]; then
-  "${build}/mincore.o"
-  echo
-fi
+make run || echo "build failed!"
